# Generated by Django 5.0.6 on 2024-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('system', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('group', 'title')},
        ),
    ]
