# Generated by Django 5.0.6 on 2024-06-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_homework_description'),
        ('system', '0007_teacher_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='system.group'),
        ),
    ]
