# Generated by Django 5.0.6 on 2024-06-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
